<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form" action="<?php echo $this->getFormAction(); ?>" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
         data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
            <    legend class="legend"><span>Book Detail</span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span>Title</span></label>
                            <div class="control">
                            <input name="title" id="Title" title="Title" value="" class="input-text" type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field required">
                            <label class="label" for="content"><span>content</span></label>
                            <div class="control">
                                <textarea name="content" id="content" rows="5" cols="8" class="input-text" data-validate="{required:true}"></textarea>
                            </div>
                        </div>
                        <div class="field date required">
                            <label class="label" for="publish_date"><span>Publish Date</span></label>
                            <div class="control">
                                <input type="text" name="publish_date" id="datepicker"  data-validate="{required:true}">
                            </div>
                        </div>
                    </div>
            </fieldset>
            </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="Save"><span>Save</span></button>
            </div>
        </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    require(["jquery", "mage/calendar"], function($){
    $("#datepicker").calendar({
        showsTime: false,
        dateFormat: "M/d/Y",
        yearRange: "-120y:c+nn",
        maxDate: "-1d", changeMonth: true, changeYear: true})
    });
</script>